# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
###
# Welcome to the new js2coffee 2.0, now
# rewritten to use the esprima parser.
# try it out!
###

$.fn.upform = ->
  $this = $(this)
  container = $this.find('.upform-main')

  reinitState = (e) ->
    $(container).find('.input-block').removeClass 'active'
    $(container).find('.input-block input').each ->
      $(this).blur()
      return
    $(e).addClass 'active'

    $(e).find('input').focus();

    return

  rescroll = (e) ->
    window.scrollTo $(e), 200,
      offset:
        left: 100
        top: -200
      queue: false
    return

  reinit = (e) ->
    reinitState e
    rescroll e
    return

  moveNext = (e) ->
    $(e).parent().parent().next().click()
    return

  movePrev = (e) ->
    $(e).parent().parent().prev().click()
    return

  $(document).ready ->
    $(container).find('.input-block').first().click()
    return
  $($this).find('form').submit ->
    false
  $(container).find('.input-block').not('.input-block input').on 'click', ->
    console.log('click', container)
    rescroll this
    return
  $(container).find('.input-block input').keypress (e) ->
    if e.which == 13
      if $(this).hasClass('required') and $(this).val() == ''
      else
        moveNext this
    return
  $(container).find('.input-block input[type="radio"]').change (e) ->
    moveNext this
    return
  $(window).on 'scroll', ->
    $(container).find('.input-block').each ->
      etop = $(this).offset().top
      diff = etop - $(window).scrollTop()
      if diff > 100 and diff < 300
        reinitState this
      return
    return
  return

# ---
# generated by js2coffee 2.2.0
